[book]
authors = ["ECOTWIN Team"]
language = "en"
src = "docs"
title = "ECOTWIN Reference Architecture"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["assets/js/mermaid.min.js", "assets/js/mermaid-init.js"]
additional-css = ["assets/css/acc.css"]
