replicaCount: 1

image:
  repository: ghcr.io/platform-mesh/ianus-controller
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Controller configuration
controller:
  endpointSlice: "ianus.platform-mesh.io"

# kcp kubeconfig secret
kubeconfig:
  secretName: "ianus-controller-kubeconfig"
  secretKey: "kubeconfig"
