#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "fastapi",
#     "uvicorn[standard]",
#     "ecotwin",
# ]
#
# [tool.uv.sources]
# ecotwin = { path = "../", editable = true }
# ///

from ecotwin.api_server import main


if __name__ == "__main__":
    main()
