apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ianus-controller
subjects:
  - kind: ServiceAccount
    name: ianus-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: ianus-controller
  apiGroup: rbac.authorization.k8s.io
