apiVersion: v1
kind: Secret
metadata:
  name: ianus-controller-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: ianus-controller
type: kubernetes.io/service-account-token
